<?php

namespace Proxies\__CG__\ExpensesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Users extends \ExpensesBundle\Entity\Users implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'imie', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'nazwisko', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'adres', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'telefon', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'email', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'pokoj', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'id');
        }

        return array('__isInitialized__', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'imie', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'nazwisko', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'adres', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'telefon', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'email', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'pokoj', '' . "\0" . 'ExpensesBundle\\Entity\\Users' . "\0" . 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Users $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setImie($imie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImie', array($imie));

        return parent::setImie($imie);
    }

    /**
     * {@inheritDoc}
     */
    public function getImie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImie', array());

        return parent::getImie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNazwisko($nazwisko)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNazwisko', array($nazwisko));

        return parent::setNazwisko($nazwisko);
    }

    /**
     * {@inheritDoc}
     */
    public function getNazwisko()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNazwisko', array());

        return parent::getNazwisko();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdres($adres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdres', array($adres));

        return parent::setAdres($adres);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdres', array());

        return parent::getAdres();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefon($telefon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefon', array($telefon));

        return parent::setTelefon($telefon);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefon', array());

        return parent::getTelefon();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPokoj($pokoj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPokoj', array($pokoj));

        return parent::setPokoj($pokoj);
    }

    /**
     * {@inheritDoc}
     */
    public function getPokoj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPokoj', array());

        return parent::getPokoj();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
